apiVersion: v1
kind: Namespace
metadata:
  name: rabbi-ahamed
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbi-ahamed-deployment
  namespace: rabbi-ahamed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rabbi-ahamed-app
  template:
    metadata:
      labels:
        app: rabbi-ahamed-app
    spec:
      containers:
      - name: rabbi-ahamed-container
        image: rabbi728/rabbi-k8:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: rabbi-ahamed-service
  namespace: rabbi-ahamed
spec:
  type: ClusterIP
  selector:
    app: rabbi-ahamed-app
  ports:
  - port: 8000
    targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rabbi-ahamed-ingress
  namespace: rabbi-ahamed
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - chat-k8s.rabbi-ahamed.site
  rules:
  - host: chat-k8s.rabbi-ahamed.site
    http:
      paths:
      - path: /chat-k8s
        pathType: Prefix
        backend:
          service:
            name: rabbi-ahamed-service
            port:
              number: 8000
